version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "4000:3306"
    volumes:
      - ./storage:/var/lib/mysql
    networks:
      - my-network

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    restart: unless-stopped
    ports: 
      - "5000:5000"
    env_file: .env
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
